### ISSUE TITLE
The following entities have state class 'measurement' but 'last_reset' is missing

### ISSUE THREAD

**Issue by Xalio** [mdeweerd/MetersToHA#5]
Bonjour,
L’intégration dans le tableau de bord d’énergie sur HA ne fonctionne pas pour la valeur historisée avec le message:
« The following entities have state class 'measurement' but 'last_reset' is missing »
La valeur journalière fonctionne.
Capture d’écran en PJ.
merci
Nicolas
![IMG_5047](https://user-images.githubusercontent.com/774362/233073144-900387f8-de8e-4e1b-ac03-4c9e806b68f6.png)

**Comment by mdeweerd** [comment]
On ajoute juste le compteur "total", pas "period_total" mais je peux voir pour ajouter last_reset qui sera un reset à minuit le jour de la valeur.

L'idée d'origine de "period_total" est de pouvoir le visualiser dans un graphique ailleurs que le tableau "energie", pas en soi pour le comptage.

Je pense que si on mets les 2 que l'eau risque d'être compté double.

**Comment by Xalio** [comment]
Ok!
Alors comment je peux avoir des données historiques avec le period_total? La je ne vois que la dernière synchronisation.
Merci!

**Comment by mdeweerd** [comment]
Une historique par rapport au compteur total sera maintenu comme une statistique quand le compteur total est déclaré comme compteur "energie".

Sinon, ces "state" ne sont pas des vraies entités (appris suite à une discussion sur le forum anglais), car pour cela il faut un objet python derrière - chose qui peut être obtenu en le faisant correspondra avec un sensor (à priori), mais je n'ai pas eu le temps d'expérimenter cela (voir [entrée sur le forum hacf](https://forum.hacf.fr/t/veolia-idf-sedif-suivi-consommation-eau-potable/11492/119?u=le_top) ).

Cela dit, même les "state" ont une historique assez court-terme - mais ils sont maintenus dans les statistiques.   Dans mon interface j'ai défini un onglet comme ceci:

```yaml
  - title: STATS
    path: stats
    type: panel
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - chart_type: line
            period: day
            days_to_show: 120
            type: statistics-graph
            entities:
              - sensor.veolia_ID_period_total
            stat_types:
              - mean
              - min
              - max
              - sum
```

qui résulte en ce graphique:

![image](https://user-images.githubusercontent.com/1504752/233188832-b0c5d00f-17c3-477a-b764-95be52526bcc.png)

J'ai donc bien une historique long terme avec survie au redémarrages (je viens de faire une mise à jour pour le revérifier).

Par contre, l'historique d'avant le premier chargement n'est pas inséré dans Home Assistant.  Il apparait qu'il y a une méthode maintenant, mais cela reste également à tester & mettre en oeuvre.
